name: Build .NET Solution

on:
  push:
    branches: [ "dev" ]
  pull_request:

env:
  OUTPUT_FOLDER_PATH: ${{ github.workspace }}/output
  EXILED_REFERENCES: ${{ github.workspace }}/references
  EXILED_DEV_REFERENCES: ${{ github.workspace }}/devreferences
  SERVER_LOCATION: /home/grosserv/SCPSL/
jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: |
          SLN=$(find . -name "*.sln" | head -n 1)
          nuget restore "$SLN"


      - name : Fill Exiled References
        run: |
          find ${{env.SERVER_LOCATION}}/SCPSL_Data/Managed/ -name "*.dll" | xargs cp -t ${{env.EXILED_REFERENCES}}

      - name: Build solution
        run: |
          mkdir ${{ env.EXILED_REFERENCES }}
          mkdir ${{ env.EXILED_DEV_REFERENCES }}

        
          export EXILED_REFERENCES=${{ env.EXILED_REFERENCES }}
          export EXILED_DEV_REFERENCES=${{ env.EXILED_DEV_REFERENCES }}
          
          msbuild "$SLN" /p:Configuration=Release

      - name: Copy DLLs to custom folder
        run: |
          mkdir -p ${{ env.OUTPUT_FOLDER_PATH }}
          find . -path "*/bin/Release/*.dll" -exec cp {} ${{ env.OUTPUT_FOLDER_PATH }} \;
