name: Build .NET Solution

on:
  push:
    branches: [ "dev" ]
  pull_request:

env:
  OUTPUT_FOLDER_PATH: ${{ github.workspace }}/output
  
jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete msbuild
        

      - name: Build solution
        run: |
          export EXILED_REFERENCES=${{ github.workspace }}/references
          export EXILED_DEV_REFERENCES=${{ github.workspace }}/devreferences
          msbuild YourSolution.sln /p:Configuration=Release

      - name: Copy DLLs to custom folder
        run: |
          mkdir -p ${{ env.OUTPUT_FOLDER_PATH }}
          find . -path "*/bin/Release/*.dll" -exec cp {} ${{ env.OUTPUT_FOLDER_PATH }} \;
