name: Build .NET Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  OUTPUT_FOLDER_PATH: /home/grosserv/.config/EXILED/Plugins/
  EXILED_REFERENCES: ${{ github.workspace }}/references
  EXILED_DEV_REFERENCES: ${{ github.workspace }}/devreferences
  SERVER_LOCATION: /home/grosserv/SCPSL/
  OTHER_DEPENDENCIES: /home/grosserv/OtherDependencies/
jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        run: |
          SLN=$(find . -name "*.sln" | head -n 1)
          nuget restore "$SLN"


      - name : Fill Exiled References
        run: |
          mkdir ${{ env.EXILED_REFERENCES }}
          mkdir ${{ env.EXILED_DEV_REFERENCES }}
          find ${{env.SERVER_LOCATION}}/SCPSL_Data/Managed/ -name "*.dll" | xargs cp -t ${{env.EXILED_REFERENCES}}
          find ${{env.OTHER_DEPENDENCIES}} -name "*.dll" | xargs cp -t ${{env.EXILED_REFERENCES}}

      - name: Build solution
        run: |
          export EXILED_REFERENCES=${{ env.EXILED_REFERENCES }}
          export EXILED_DEV_REFERENCES=${{ env.EXILED_DEV_REFERENCES }}
          SLN=$(find . -name "*.sln" | head -n 1)
          msbuild "$SLN" /p:Configuration=Release

      - name: Copy plugin to server
        if: github.event_name == 'push'
        run: |
          DLL=$(find . -path "*/bin/Release/*KruacentExiled.dll" | head -n 1)
      
          if [ -z "$DLL" ]; then
            echo "DLL not found!"
            exit 1
          fi
          cp "$DLL" $OUTPUT_FOLDER_PATH/

      - name: Create GitHub Release Draft
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: draft-${{ github.sha }}
          name: "Draft Release"
          draft: true
          files: "**/bin/Release/*KruacentExiled.dll"
          generate_release_notes: false
